apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gpkl6u6ya-java-springboot-gitops-repository
spec:
  url: https://github.com/rhopp-rhtap-testing/gpkl6u6ya-java-springboot-gitops